server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://hasdsd.cn:3307/qxj?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        hikari:
            connection-timeout: 10000
            validation-timeout: 3000
            idle-timeout: 60000
            login-timeout: 5
            max-lifetime: 60000
            maximum-pool-size: 10
            minimum-idle: 5
            read-only: false
